### ISSUE TITLE
Throwing "Exception: Library could not be loaded!" on my ubuntu operating system of server, but working on virtual box ubuntu os.

### ISSUE THREAD

**Issue by rahul-badgujar** [jonasroussel/system_resources#1]
I am trying to use this package to analyze the resources usage by my server when it handles loads. So for that, I used this package and the 2 methods to get average CPU load and average memory load. I had tested them on my ubuntu installed at the virtual box in my local machine at it was working well. But when I deploy my dart app to server with the same code, it throws an Exception
`Exception: Library could not be loaded!` when I call the average usage getting methods.
I checked the versions of Ubuntu on both the systems and they are the same i.e., Ubuntu LTS 20.04.
Please look at this issue as I am not able to use it.

**Comment by jonasroussel** [comment]
Hello,

I'm currently working hard on a professional project, so I can't work on this issue now. Everything I know for the moment, is that come from this line :

https://github.com/jonasroussel/system_resources/blob/3222666732c225c360ff7a329b9a84185bee8f62/lib/src/dylib.dart#L44

And the dart library fail to load the C library located in the build directory.

You can fork, and try to resolve this issue if you want.
If the issue isn't solve, I can work on, at the end of the month.
