### ISSUE TITLE
not working on iOS

### ISSUE THREAD

**Issue by FreeStyle212** [jonasroussel/system_resources#4]
Hi, I'm not sure you intend this to work on iOS?

I tried to run it on iOS simulator but got an error telling me to first call SystemResources.init()

But after I do this I then get another error: Unhandled Exception: Unsupported operation: Isolate.resolvePackageUri

Sorry to bother you if it's not meant to work on iOS

**Comment by jonasroussel** [comment]
Hi ! No problem, thanks for your question, but yes, I didn't intend to make it work with Flutter globally, I made it to be used with a Dart server.

**Comment by FreeStyle212** [comment]
Hi Jonas,

Thanks for your reply. Interesting, so you have experience of writing server code in Dart?

I am just now writing a server in Dart, using 'get_server'. Do you have any advice from your experiences, or any good articles you can share, example projects that you know of?

It's nice to be in contact with a proper Flutter dev. I've been doing this myself for about 3 years now, but you are at a level above me. Be good if we could stay in touch :)

Dan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
